### ISSUE TITLE
github: Be able to create Org groups/users source file.

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj-contribs#35]
If the Forjfile given set org users and groups, the github plugin do not set it in github.yaml

Have:
```yaml
users: {}
groups: {}
```

Should have:
```yaml
users: {}
groups: 
  Core: 
    role: none
    users: [ "clarsonneur", "ojacques", "wenlock", "homeles", "arneluehrs", "miqui" ]
  Contributors:
    users: [ "vaceletm" ]
  gerrit:
    users: [ "forj-publish" ]
```
